name: Ping Render Server

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Render
        run: curl -I https://your-backend-url.onrender.com/ 